name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            generator: Xcode
          - os: ubuntu-latest
            generator: Ninja Multi-Config
          - os: windows-latest
            generator: Visual Studio 18 2026
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -G "${{ matrix.generator }}" -DSOLVER_BUILD_TESTS=ON

      - name: Build CMake
        run: cmake --build build --config Release --target libsolver-tests

      - name: Run tests
        run: ctest --test-dir build -C Release --output-on-failure
